### ISSUE TITLE
Download icons for matrix files on Files tab

### ISSUE THREAD

**Issue by gabsie** [HumanCellAtlas/dcp-feedback#5]
In order to complete a task about downloading a matrix, the participant tried first the file tab on a project and tried to download .matrix files from there.
They start rotating and then end up with a red x.
Problem: the affordance of a download icon presumes a download is possible, but it doesn't work as per user expectation.
Solution: 1. definitely remove these icons from there if they are not going to provide this ability, as they are confusing as they are. 2. come up, generally, with a solution which would allow to download easy light files straight from the browser.

**Comment by kozbo** [comment]
@theathorn

**Comment by adriennes** [comment]
Adding that this impacted P8 from the beta test as well

**Comment by theathorn** [comment]
Single file download of "matrix" file types is disabled as per humancellatlas/data-browser#405.

**Comment by NoopDog** [comment]
@adriennes this should be fixed on prod. Please close if this looks ok to you. Specifically, the download icons are not shown for matrix files.

**Comment by adriennes** [comment]
@gabsie for review
I think we need to think through this flow, there are still some issues here that make accessing a matrix confusing.  As a user, let's say I want a matrix so I go to "File Type" and select ".matrix".   Now I can see these in the Files view, but it's still not clear to me how to access them.  We need to fully sketch out how we intend this journey to work.
